### ISSUE TITLE
Implement similar functionality but for discord, please (if possible) 

### ISSUE THREAD

**Issue by DGKSK8LIFE** [sampoder/pfp#9]

**Comment by sampoder** [comment]
I've been wanting to do this for a while, do you know an API endpoint to change pfp?

**Comment by DGKSK8LIFE** [comment]
Hmm, doesn't seem like there is any official api endpoint to do this in discord. https://github.com/cacheiforindicium/Discord-Avatar-Rotator; that's in powershell and C# and technically against discord TOS. You could do some DOM scripting. You also might want to take a look at [betterdiscord](https://betterdiscord.net/home/); its extra functionality and options for custom theming/css/js might make it easier to test and debug implementing said feature.

**Comment by sampoder** [comment]
Hmm tbh, I don't really want to break any TOS :/
